# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-31 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_reply_thread'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='slug',
            field=models.SlugField(default='', editable=False, max_length=100, unique=True, verbose_name='Identificador'),
        ),
    ]
