# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-31 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_thread_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='slug',
            field=models.SlugField(verbose_name='Identificador'),
        ),
    ]
